spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          vk:
            client-name: vk
            client-id: ${VK_AUTH_CLIENT_ID}
            client-secret: ${VK_AUTH_CLIENT_SECRET}
            provider: vk
            redirect-uri: http://localhost:8080/login/oauth2/code/vk
            authorization-grant-type: authorization_code
            client-authentication-method: form
            scope: email

        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token?client_secret=${VK_AUTH_CLIENT_SECRET}
            user-info-uri: https://api.vk.com/method/users.get?v=5.52&{user_id}
            user-name-attribute: user_id

logging:
  level:
    com.vk.api.sdk.httpclient: error
    root: info

